### ISSUE TITLE
Furigana is invisible on dark mode

### ISSUE THREAD

**Issue by huangziwei** [larvata/mirigana#10]
mirigana v0.20 on Firefox 78.0.2, MacOS 10.15.5

Light:

<img width="600" alt="Screenshot 2020-07-23 at 17 34 57" src="https://user-images.githubusercontent.com/3627182/88306614-3d008500-cd0b-11ea-8076-a54af812c03d.png">

Dark:

<img width="601" alt="Screenshot 2020-07-23 at 17 35 09" src="https://user-images.githubusercontent.com/3627182/88306636-44c02980-cd0b-11ea-9515-0aa042800638.png">

**Comment by larvata** [comment]
Thank you for your feedback!

Version 0.22 has been published for the firefox.
The chrome version will be available after the review.

New font color `white` was added.
You can choose it in the popup window from your address bar.

**Comment by huangziwei** [comment]
Thanks.

**Comment by SpectreAX** [comment]
> Thank you for your feedback!
> 
> Version 0.22 has been published for the firefox. The chrome version will be available after the review.
> 
> New font color `white` was added. You can choose it in the popup window from your address bar.

I cannot find the option to set the font color in latest verison(1.5.0).
Furigana become invisible on dark mode again.
